### PR TITLE
Simplify linux build.

### PR DESCRIPTION
**Pull request by charmyt**
Simplify linux build

### CODE REVIEW

**Comment by zethon** [comment]
I don't want to pollute the root folder with platform specific scripts. Create a `builds/linux` folder and put the .sh files in there.

**Comment by charmyt** [comment]
If I have to start keeping these in subdirs then I guess they don't really help me much.
I'll just keep them as local tools.

**Comment by zethon** [comment]
Other people still find the useful. It's just good practice to keep platform specific items in their own folders. 🤷

**Comment by charmyt** [comment]
We are putting the "build" folder at the root of the git clone (which is fine, it's in .gitignore anyway)
You want a "builds" folder at that level too? 

I was thinking you might have something like build.sh which would work on OSX and *nix, and then something like build.bat which would work on windows. Since cmake is so clunky.

**Comment by zethon** [comment]
I generally use "builds" as my build folder (though I sometimes use "bin" too). Maybe you're right, "build" and "builds" is too close. Maybe call it "tools"? So `tools/linux`?

Naming is the hardest part of programming!

**Comment by charmyt** [comment]
I'm okay with changing it to "tools".

We move it out of the root dir and then we need to start checking where people are running it from, since we are cd'ing into other directories.
So I'll add something like `GIT_ROOT=$(git rev-parse --show-toplevel)`

**Pull request closed without merging**
